Generating frontier for markets:   0%|                                                                             | 0/20 [00:00<?, ?it/s]
Checking buy side options:   0%|                                                                                   | 0/23 [00:00<?, ?it/s]
There are 25 buy orders and 25 sell orders
#####Generating combinatorial/book/STOCK_2_SEED_2_book_AAPL_MSFT.npy with size 50 and noise 0.015625#####
Starting async computation for iteration 0
Set parameter Username
Academic license - for non-commercial use only - expires 2025-11-08
RangeIndex(start=0, stop=25, step=1) {2, 15}
RangeIndex(start=0, stop=25, step=1) {4, 8, 9, 10, 15, 19, 20, 22}
23






Checking buy side options: 100%|██████████████████████████████████████████████████████████████████████████| 23/23 [00:13<00:00,  1.61it/s]



Checking sell side options:  76%|███████████████████████████████████████████████████████▊                 | 13/17 [00:07<00:02,  1.88it/s]
RangeIndex(start=0, stop=7, step=1)
> /common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor.py(503)<module>()

Checking sell side options: 100%|█████████████████████████████████████████████████████████████████████████| 17/17 [00:09<00:00,  2.04it/s]
> /common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor.py(504)<module>()
-> breakpoint()
> /common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor.py(505)<module>()
-> opt_sell_book_new = frontier_option_label_attempt_1[frontier_option_label_attempt_1[:, -2]==0].iloc[:,:-1]
pandas.errors.InvalidIndexError: (slice(None, None, None), -2)
> /common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor.py(505)<module>()
Generating frontier for markets:   0%|                                                                             | 0/20 [01:09<?, ?it/s]
Traceback (most recent call last):
  File "/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor.py", line 505, in <module>
    opt_sell_book_new = frontier_option_label_attempt_1[frontier_option_label_attempt_1[:, -2]==0].iloc[:,:-1]
  File "/common/home/hg343/anaconda3/lib/python3.9/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/common/home/hg343/anaconda3/lib/python3.9/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit