2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Configure stats pid to 105716
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/.config/wandb/settings
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/Research/accelerate_combo_option/src/wandb/settings
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/combo_stock_frontier_data_preprocessor_forked.py', 'program_abspath': '/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor_forked.py', 'program': '/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor_forked.py'}
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:_log_setup():520] Logging user logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250324_123017-8ivqqdzz/logs/debug.log
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:_log_setup():521] Logging internal logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250324_123017-8ivqqdzz/logs/debug-internal.log
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:init():560] calling init triggers
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:init():610] starting backend
2025-03-24 12:30:17,699 INFO    MainThread:105716 [wandb_init.py:init():614] setting up manager
2025-03-24 12:30:17,701 INFO    MainThread:105716 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 12:30:17,703 INFO    MainThread:105716 [wandb_init.py:init():622] backend started and connected
2025-03-24 12:30:17,707 INFO    MainThread:105716 [wandb_init.py:init():711] updated telemetry
2025-03-24 12:30:17,726 INFO    MainThread:105716 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-03-24 12:30:17,959 INFO    MainThread:105716 [wandb_run.py:_on_init():2396] communicating current version
2025-03-24 12:30:18,004 INFO    MainThread:105716 [wandb_run.py:_on_init():2405] got version response upgrade_message: "wandb version 0.19.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-03-24 12:30:18,005 INFO    MainThread:105716 [wandb_init.py:init():795] starting run threads in backend
2025-03-24 12:30:31,446 INFO    MainThread:105716 [wandb_run.py:_console_start():2374] atexit reg
2025-03-24 12:30:31,447 INFO    MainThread:105716 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2025-03-24 12:30:31,447 INFO    MainThread:105716 [wandb_run.py:_redirect():2294] Wrapping output streams.
2025-03-24 12:30:31,447 INFO    MainThread:105716 [wandb_run.py:_redirect():2319] Redirects installed.
2025-03-24 12:30:31,449 INFO    MainThread:105716 [wandb_init.py:init():838] run started, returning control to user process
2025-03-24 12:30:45,411 INFO    MainThread:105716 [wandb_run.py:_finish():2103] finishing run jglppk/expediating_comb_financial_market_matching/8ivqqdzz
2025-03-24 12:30:45,412 INFO    MainThread:105716 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 1
2025-03-24 12:30:45,413 INFO    MainThread:105716 [wandb_run.py:_restore():2326] restore
2025-03-24 12:30:45,413 INFO    MainThread:105716 [wandb_run.py:_restore():2332] restore done
2025-03-24 12:30:51,109 INFO    MainThread:105716 [wandb_run.py:_restore():2326] restore
2025-03-24 12:30:51,109 INFO    MainThread:105716 [wandb_run.py:_restore():2332] restore done
2025-03-24 12:30:52,113 ERROR   MainThread:105716 [wandb_run.py:_atexit_cleanup():2352] Problem finishing run
Traceback (most recent call last):
  File "/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor_forked.py", line 161, in <module>
    market.remove_matched_orders()
  File "/common/home/hg343/Research/accelerate_combo_option/src/market.py", line 61, in remove_matched_orders
    _, _, _, isMatch, matched_order_index =  self.apply_mechanism(orders, offset = False, show_matched_orders=True)
ValueError: not enough values to unpack (expected 5, got 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2352, in _atexit_cleanup
    self._on_finish()
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2608, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/common/home/hg343/anaconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/common/home/hg343/anaconda3/lib/python3.9/threading.py", line 319, in wait
    return gotit
  File "/common/home/hg343/anaconda3/lib/python3.9/threading.py", line 319, in wait
    return gotit
  File "/common/home/hg343/anaconda3/lib/python3.9/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/common/home/hg343/anaconda3/lib/python3.9/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
